name: "Tests"

on: [pull_request]
jobs:
  lint:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3', 'nightly']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PHP ${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --no-progress --no-suggest

    - name: Run Tests
      run: vendor/bin/phpunit --configuration phpunit.xml